#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-deployment
  template:
    metadata:
      labels:
        app: application-deployment
    spec:
      containers:
        - name: main
          image: <image name goes here>
          imagePullPolicy: Always 
          envFrom:
            - configMapRef:
                name: app-fabric-org1-v1-map
          resources:
            requests:
              memory: "50Mi"
              cpu: "0.1"
          volumeMounts:
            - name: fabricids
              mountPath: /fabric/application/wallet
            - name: fabric-ccp
              mountPath: /fabric/application/gateways            
            - name: tlscerts
              mountPath: /fabric/tlscacerts
            - name: assets-volume
              mountPath: /assets
            - name: encrypted-assets-volume
              mountPath: /encrypted-assets
        - name: asset-encrypter
          image: localhost:5000/asset-encrypter:latest
          volumeMounts:
            - name: assets-volume
              mountPath: /assets
            - name: encrypted-assets-volume
              mountPath: /assets-encrypted
      volumes:
        - name: fabric-ccp
          configMap:
            name: app-fabric-ccp-v1-map
        - name: fabricids
          configMap:
            name: app-fabric-ids-v1-map
        - name: tlscerts
          configMap:
            name: app-fabric-tls-v1-map
        - name: assets-volume
          persistentVolumeClaim:
            claimName: fabric-org1-assets
        - name: encrypted-assets-volume
          persistentVolumeClaim:
            claimName: fabric-org1-encrypted