apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fabric-org1-assets
  namespace: ${NS}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${STORAGE_CLASS}
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fabric-org1-encrypted-assets
  namespace: ${NS}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${STORAGE_CLASS}
  resources:
    requests:
      storage: 1Gi